language: python

sudo: false

python:
- "3.6"

#addons:
#  apt:
#    packages:
#    - python3-venv

before_install:
- python3 -m venv venv/
- source venv/bin/activate

install:
- source venv/bin/activate
- pip3 install -r requirements.txt
- pip3 install mypy

script:
- source venv/bin/activate
- ./mypyall.py
