language: python

sudo: false

python:
- "3.6"

addons:
  apt:
    packages:
    - python3-venv

before_install:
- python3 -m venv venv/
- source venv/bin/activate

install:
- pip install -r requirements.txt
- pip install mypy

script:
- ./mypyall.py
