token: UNSET

commloop:
    address: localhost
    port: 1679 # Thanks random.org
    auth: UNSET

owner:
    id: 0

nudges:
    password: UNSET

mainserver:
    id: 0

    channels:
        admin: 0
        main: 0
        changelog: 0

    roles:
        admin: 0
        coder: 0

gameservers:
    default: "main"

    main:
        address: ""
        port: 0
    
    test:
        address: ""
        port: 0