token: UNSET

commloop:
    address: localhost
    port: 1679 # Thanks random.org
    auth: UNSET

owner:
    id: 0

nudges:
    password: UNSET

mainserver:
    id: 0

    channels:
        admin: 0
        main: 0
        changelog: 0
        code: 0

    roles:
        admin: 0
        coder: 0

    irc:
        irc:
            address: unset
            port: 6697
            channel: "#unset"

            user:
                name: unset
                realname: unset
                nick: unset

        discord:
            channel: 0

gameservers:
    default: "main"

    main:
        address: ""
        port: 0

    test:
        address: ""
        port: 0

github:
    login:
        token: UNSET

    repo:
        # Username of the user that owns the repo.
        owner: UNSET
        # Name of the repo.
        name: UNSET

        branch: UNSET

        labels:
            secret_conflict: "Unset"

        secret_repo_files:
            - "unset"
